# -*- coding: utf-8 -*-
"""test_cases.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0G0vqyM4XUyD_hlr8AjITBpO_WWmTUZ
"""

requests = [
    {
        "material": "cement",
        "quantity": 70,
        "priority": "High",
        "inventory": 100,
        "vehicle": True
    },
    {
        "material": "steel",
        "quantity": 120,
        "priority": "High",
        "inventory": 50,
        "vehicle": True
    },
    {
        "material": "bricks",
        "quantity": 3000,
        "priority": "Low",
        "inventory": 5000,
        "vehicle": False
    },
    {
        "material": "cement",
        "quantity": 20,
        "priority": "Medium",
        "inventory": 20,
        "vehicle": True
    }
]