import json
import os
import time
from dotenv import load_dotenv
from google import genai
from google.genai.errors import ClientError

from schema import validate_schema
from tools import ALLOWED_ACTIONS

# Constraint: Maximum reasoning budget
MAX_STEPS = 5

load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY not found in .env file")

client = genai.Client(api_key=api_key)


class ConstrainedReActAgent:

    def __init__(self, inventory_db):
        self.inventory = inventory_db

    def think_and_act(self, request):

        material = request.get("material")
        quantity = request.get("quantity", 0)
        current_inv = self.inventory.get(material, 0)

        prompt = f"""
You are a Constrained ReAct Agent responsible for coordinating
material deliveries for a construction company.

Current Request:
- Material Requested: {material}
- Quantity Requested: {quantity}
- Current Inventory Available: {current_inv}
- Request Priority: {request.get("priority", "Low")}
- Vehicle Available: {request.get("vehicle", False)}

Constraints:

1. You may use ONLY the following tools:
   - check_inventory
   - check_vehicle
   - dispatch_material
   - schedule_delivery

2. Do NOT invent or use any other tools.

3. Your reasoning is limited to a maximum of {MAX_STEPS} steps.

4. If you cannot confidently reach a decision,
   return status = "ESCALATE".

Return ONLY a valid JSON object that follows exactly this schema:

{{
    "thought": "...",
    "action": "Deliver Immediately | Wait for Restock | Schedule Vehicle | Review System Logs",
    "status": "APPROVED | PENDING | REJECTED | SCHEDULED | ESCALATE"
}}
"""

        max_retries = 5
        response = None

        for attempt in range(max_retries):

            try:

                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=prompt
                )

                break

            except ClientError as e:

                if "429" in str(e):

                    wait_time = (attempt + 1) * 10

                    print(
                        f"Rate limit hit. Waiting {wait_time}s "
                        f"(Attempt {attempt + 1}/{max_retries})..."
                    )

                    time.sleep(wait_time)

                else:
                    raise e

        if not response:

            return {
                "thought": "No response received.",
                "action": "Review System Logs",
                "status": "ESCALATE"
            }

        try:

            cleaned_text = (
                response.text
                .strip()
                .replace("```json", "")
                .replace("```", "")
            )

            decision = json.loads(cleaned_text)

        except Exception:

            return {
                "thought": response.text,
                "action": "Review System Logs",
                "status": "ESCALATE"
            }

        # -----------------------------
        # Constraint 1
        # Validate JSON Schema
        # -----------------------------

        if not validate_schema(decision):

            return {
                "thought": "Invalid response schema.",
                "action": "Review System Logs",
                "status": "ESCALATE"
            }

        # -----------------------------
        # Constraint 2
        # Validate Allowed Actions
        # -----------------------------

        if decision.get("action") not in ALLOWED_ACTIONS:

            return {
                "thought": "The action generated by the model is not allowed.",
                "action": "Review System Logs",
                "status": "ESCALATE"
            }
        # -----------------------------
        # Constraint 3
        # Update inventory only if approved
        # -----------------------------

        if (
            decision.get("status", "")
            and current_inv >= quantity
        ):
            self.inventory[material] -= quantity

        # -----------------------------
        # Add remaining inventory
        # -----------------------------

        decision["remaining_inventory"] = self.inventory.get(
            material,
            current_inv
        )

        time.sleep(3)

        return decision


if __name__ == "__main__":

    from test_cases import requests

    initial_inventory = {
        "cement": 100,
        "steel": 50,
        "bricks": 5000,
    }

    agent = ConstrainedReActAgent(
        inventory_db=initial_inventory
    )

    print("\nProcessing Constrained ReAct Agent Decisions\n")

    for idx, req in enumerate(requests, 1):

        print("=" * 60)
        print(f"Request {idx}")
        print(req)

        result = agent.think_and_act(req)

        print(f"Thought : {result.get('thought')}")
        print(f"Action  : {result.get('action')}")
        print(f"Status  : {result.get('status')}")
        print(
            f"Remaining Inventory : "
            f"{result.get('remaining_inventory')}"
        )

    print("=" * 60)