# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dn7hOOgUZnCP6VeK8D74N7boXxvc_zQL
"""

from test_cases import requests
def reactive_agent(request):
    # Rule 1: Check inventory
    if request["inventory"] < request["quantity"]:
        return "Insufficient Inventory. Please wait for restocking."
    # Rule 2: High-priority requests
    if request["priority"] == "High":
        if request["vehicle"]:
            return "Deliver Immediately"
        return "High Priority - Waiting for Vehicle"
    # Rule 3: Medium-priority requests
    if request["priority"] == "Medium":
        if request["vehicle"]:
            return "Deliver"
        return "Medium Priority - Please wait for vehicle."

    # Rule 4: Low-priority requests
    if request["priority"] == "Low":
        return "Wait for Scheduled Delivery"
    # Rule 5: Unknown priority
    return "Invalid Request"
for request in requests:
    print(request)
    print("Decision:", reactive_agent(request))
    print("=" * 60)