# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dn7hOOgUZnCP6VeK8D74N7boXxvc_zQL
"""

from test_cases import requests
from enum import Enum
from dotenv import load_dotenv
import google.generativeai as genai
import os

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise ValueError("GEMINI_API_KEY not found. Check your .env file.")

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.0-flash")


class Route(Enum):
    DELIVER = "DELIVER"
    QUEUE = "QUEUE"
    ESCALATE = "ESCALATE"

def route_request(request):

    prompt = f"""
You are a logistics routing AI agent.

Material:
{request["material"]}

Quantity:
{request["quantity"]}

Inventory:
{request["inventory"]}

Vehicle Available:
{request["vehicle"]}

Priority:
{request["priority"]}

Decision Rules

1. DELIVER
- Inventory is enough
- Vehicle is available

2. QUEUE
- Resources are temporarily unavailable

3. ESCALATE
- High priority
- Inventory shortage

Return ONLY:

DELIVER
QUEUE
ESCALATE
"""

    try:
        response = model.generate_content(prompt)
        decision = response.text.strip().upper()

        if decision == "DELIVER":
            return Route.DELIVER
        elif decision == "ESCALATE":
            return Route.ESCALATE
        else:
            return Route.QUEUE

    except Exception as e:
        print("Gemini Error:", e)
        return Route.QUEUE


def execute_route(route, request):
    if route == Route.DELIVER:
        return (
            f"Deliver {request['quantity']} "
            f"units of {request['material']}"
        )

    elif route == Route.QUEUE:
        return (
            f"Queue {request['material']} "
            "until resources are available"
        )

    elif route == Route.ESCALATE:
        return (
            f"Escalate {request['material']} "
            "to logistics manager"
        )


print("=" * 50)
print("Gemini Logistics Routing Agent")
print("=" * 50)

for i, request in enumerate(requests, start=1):
    route = route_request(request)
    result = execute_route(route, request)

    print("\nRequest:", i)
    print("=" * 40)
    print("Material :", request["material"])
    print("Quantity :", request["quantity"])
    print("Priority :", request["priority"])
    print("Inventory:", request["inventory"])
    print("Vehicle  :", request["vehicle"])
    print("Route    :", route.value)
    print("Action   :", result)