{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c3e0e99-4e58-40df-9c45-87201d32e782",
   "metadata": {},
   "outputs": [],
   "source": [
    "from enum import Enum\n",
    "from test_cases import requests\n",
    "from dotenv import load_dotenv\n",
    "import google.generativeai as genai\n",
    "import os\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "API_KEY = os.getenv(\"GEMINI_API_KEY\")\n",
    "\n",
    "if not API_KEY:\n",
    "    raise ValueError(\"GEMINI_API_KEY not found. Check your .env file.\")\n",
    "\n",
    "genai.configure(api_key=API_KEY)\n",
    "\n",
    "model = genai.GenerativeModel(\"gemini-2.0-flash\")\n",
    "\n",
    "\n",
    "class Route(Enum):\n",
    "    DELIVER = \"DELIVER\"\n",
    "    QUEUE = \"QUEUE\"\n",
    "    ESCALATE = \"ESCALATE\"\n",
    "    \n",
    "def route_request(request):\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "You are a logistics routing AI agent.\n",
    "\n",
    "Material:\n",
    "{request[\"material\"]}\n",
    "\n",
    "Quantity:\n",
    "{request[\"quantity\"]}\n",
    "\n",
    "Inventory:\n",
    "{request[\"inventory\"]}\n",
    "\n",
    "Vehicle Available:\n",
    "{request[\"vehicle\"]}\n",
    "\n",
    "Priority:\n",
    "{request[\"priority\"]}\n",
    "\n",
    "Decision Rules\n",
    "\n",
    "1. DELIVER\n",
    "- Inventory is enough\n",
    "- Vehicle is available\n",
    "\n",
    "2. QUEUE\n",
    "- Resources are temporarily unavailable\n",
    "\n",
    "3. ESCALATE\n",
    "- High priority\n",
    "- Inventory shortage\n",
    "\n",
    "Return ONLY:\n",
    "\n",
    "DELIVER\n",
    "QUEUE\n",
    "ESCALATE\n",
    "\"\"\"\n",
    "\n",
    "    try:\n",
    "        response = model.generate_content(prompt)\n",
    "        decision = response.text.strip().upper()\n",
    "\n",
    "        if decision == \"DELIVER\":\n",
    "            return Route.DELIVER\n",
    "        elif decision == \"ESCALATE\":\n",
    "            return Route.ESCALATE\n",
    "        else:\n",
    "            return Route.QUEUE\n",
    "\n",
    "    except Exception as e:\n",
    "        print(\"Gemini Error:\", e)\n",
    "        return Route.QUEUE\n",
    "\n",
    "\n",
    "def execute_route(route, request):\n",
    "    if route == Route.DELIVER:\n",
    "        return (\n",
    "            f\"Deliver {request['quantity']} \"\n",
    "            f\"units of {request['material']}\"\n",
    "        )\n",
    "\n",
    "    elif route == Route.QUEUE:\n",
    "        return (\n",
    "            f\"Queue {request['material']} \"\n",
    "            \"until resources are available\"\n",
    "        )\n",
    "\n",
    "    elif route == Route.ESCALATE:\n",
    "        return (\n",
    "            f\"Escalate {request['material']} \"\n",
    "            \"to logistics manager\"\n",
    "        )\n",
    "\n",
    "\n",
    "print(\"=\" * 50)\n",
    "print(\"Gemini Logistics Routing Agent\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "for i, request in enumerate(requests, start=1):\n",
    "    route = route_request(request)\n",
    "    result = execute_route(route, request)\n",
    "\n",
    "    print(\"\\nRequest:\", i)\n",
    "    print(\"=\" * 40)\n",
    "    print(\"Material :\", request[\"material\"])\n",
    "    print(\"Quantity :\", request[\"quantity\"])\n",
    "    print(\"Priority :\", request[\"priority\"])\n",
    "    print(\"Inventory:\", request[\"inventory\"])\n",
    "    print(\"Vehicle  :\", request[\"vehicle\"])\n",
    "    print(\"Route    :\", route.value)\n",
    "    print(\"Action   :\", result)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
